### ISSUE TITLE
[Feature] User Profile Creation

### ISSUE THREAD

**Issue by TanmoySG** [TanmoySG/placeholders#10]
User Profile creation for placeholders. Setup basic route.

[Checkpoints]
- [x] Setup Route `POST /users`
- [x] Pass the following JSON as request body
```json
{
  "username" : "",
  "email" : "",
  "password" : "",
}
```
- [x] JSON Request-Body Validation, Email Pattern Validation
- [x] Implement following architecture

[Architecture]

![step1-flow1](https://github.com/TanmoySG/placeholders/assets/36238254/5a95a274-ae94-40ba-8ed8-23786546e51f)

[Additional Details]

- Initial User Creation Flow (no Access Control Enforced)
  - Check if username/email exists
  - Hash password, using SHA1/MD5
  - Generate UUID for user
  - Create Default Namespace to ph-namespaces.json
  - Add User Profile to ph-systems.users.json
  - See [this diagram](./step1-flow1.jpg)
  - Fallbacks
    - Anyone can create and access any container (no route for container access is implemented, so no harm)

**Comment by pinakipb2** [comment]
>   * See [this diagram](./step1-flow1.jpg)
 Link is broken @TanmoySG

**Comment by TanmoySG** [comment]
> >   * See [this diagram](./step1-flow1.jpg)
> 👆 Link is broken @TanmoySG 

Same as that mentioned in the issue

**Comment by pinakipb2** [comment]
>   * Create Default Namespace to ph-namespaces.json
>   * Add User Profile to ph-systems.users.json

and 

`User URL` from diagram is not clear to me. @TanmoySG
